version: "3.8"

services:
  db_project:
    image: postgres:11-alpine
    container_name: db_project
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    env_file:
      - .env.dev
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: django
    command:  bash -c "python /usr/src/django_project/manage.py runserver 0.0.0.0:8000"
    entrypoint: /usr/src/django_project/docker/entrypoint.sh
    volumes:
      - .:/usr/src/django_project/
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    depends_on:
      - db_project


volumes:
  postgres_data: