# Generated by Django 4.1 on 2023-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'db_table': 'blog_page',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.URLField()),
                ('sort_order', models.IntegerField()),
                ('views_count', models.IntegerField(default=0)),
                ('pages', models.ManyToManyField(related_name='content_blocks', to='simple_blog.page')),
            ],
            options={
                'db_table': 'blog_content_block',
                'ordering': ['id'],
            },
        ),
    ]
